name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a854eaa2917b516cd32f1a3afa8c0d14be
      - uses: actions/setup-node@1e60f620b5540040260f696b1714e0cd5dd9236
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - uses: actions/upload-pages-artifact@56afc689d6040457cf68e355d4a1b9014dcebcfd
        with:
          path: docs/.vitepress/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@d6db901649a34838c31ab04d73a8d5460dd2940e