name: Deploy VitePress to GitHub Pages

on:
  push:
    branches: [ master ]  # 👈 改成你的分支 master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # 👈 不动！GitHub 服务器用的，不用管
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist  # 👈 不动！自动生成